ben_doctors:
    resource: "@BenDoctorsBundle/Resources/config/routing.yml"
    prefix:   /
ben_user:
    resource: "@BenUserBundle/Resources/config/routing.yml"
    prefix:   /
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"