<?php

namespace Ben\DoctorsBundle\Entity;

/**
 * FseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FseRepository extends \Doctrine\ORM\EntityRepository
{
    public function counter() {
        $qb = $this->createQueryBuilder('m')->select('COUNT(m)');
        return $qb->getQuery()->getSingleScalarResult();
    }
}
