<?php

namespace Ben\DoctorsBundle\Entity;

/**
 * SpecialityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialityRepository extends \Doctrine\ORM\EntityRepository
{
}
